### ISSUE TITLE
Hiya, I'm having trouble configuring your widget, can I trouble you to help me out, please?

### ISSUE THREAD

**Issue by JMarkyBB** [fitzagard/omnifocus-widget#5]
Can you help me from here Fitzagard please?

I am a pro user, so how do I configure otherwise?
![screenshot 2017-04-25 15 44 47](https://cloud.githubusercontent.com/assets/27829143/25391575/721c34c0-29ce-11e7-8452-452b41967588.png)

**Comment by fitzagard** [comment]
Can you check whether you have Pro features enabled? If you go to the OmniFocus menu, then choose "About OmniFocus," the window that opens will include a purple box - if you have pro enabled

**Comment by JMarkyBB** [comment]
Do You mean this?

![screenshot 2017-04-25 16 16 32](https://cloud.githubusercontent.com/assets/27829143/25393146/9fedd490-29d2-11e7-8ed8-830134e092a0.png)

**Comment by fitzagard** [comment]
Thanks for the screenshot. You don't have the pro version of omnifocus enabled. In order to allow scripting you'll need to upgrade (or enable if you already purchased) to the pro version of omnifocus

**Comment by JMarkyBB** [comment]
Thank you Fitzagard, I've upgraded, I thought I'd bought it when I purchased Omnifocus in the first place, obviously I hadn't.
Thanks for your help and quick response.
Its appreciated.

**Comment by JMarkyBB** [comment]
That is sweet, can I configure it to show Contexts or Projects?

**Comment by fitzagard** [comment]
@JMarkyBB I'm glad its working for you now. If  context and project are set for a task they will show underneath it. Enjoy!
